### ISSUE TITLE
[Feature request] Support Spring Boot 3.0 and GraalVM Native Image

### ISSUE THREAD

**Issue by ksilz** [spring-projects/spring-petclinic#1109]
With Spring Boot 3.0 just around the corner, are there any plans to migrate this app to Spring Boot 3? Of special interest to me is native compilation with GraalVM Native Image. So I'd love to see Pet Clinic as a native executable!

**Comment by anthonydahanne** [comment]
hello,
You can already try it out (spring boot 3 native build).
I've just checked out the branch name `springboot3`  and then applied this patch:

```
diff --git a/pom.xml b/pom.xml
index 4de642c..dcb2caa 100644
--- a/pom.xml
+++ b/pom.xml
@@ -8,7 +8,7 @@
   <parent>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-parent</artifactId>
-    <version>3.0.0-RC1</version>
+    <version>3.0.0</version>
   </parent>
   <name>petclinic</name>
 
@@ -116,6 +116,18 @@
 
   <build>
     <plugins>
+      <plugin>
+        <groupId>org.springframework.boot</groupId>
+        <artifactId>spring-boot-maven-plugin</artifactId>
+            <configuration>
+              <image>
+                 <env>
+                    <BP_JVM_VERSION>17</BP_JVM_VERSION>
+                    <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
+                 </env>
+              </image>
+            </configuration>
+      </plugin>
       <plugin>
         <groupId>io.spring.javaformat</groupId>
         <artifactId>spring-javaformat-maven-plugin</artifactId>
```

and run the build with:
` ./mvnw spring-boot:build-image -DskipTests`

It seems to have failed though :-/

```
[...]
[INFO]     [creator]     Paketo Buildpack for Native Image 5.6.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/native-image
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_BINARY_COMPRESSION_METHOD                Compression mechanism used to reduce binary size. Options: `none` (default), `upx` or `gzexe`
[INFO]     [creator]         $BP_NATIVE_IMAGE                       true  enable native image build
[INFO]     [creator]         $BP_NATIVE_IMAGE_BUILD_ARGUMENTS             arguments to pass to the native-image command
[INFO]     [creator]         $BP_NATIVE_IMAGE_BUILD_ARGUMENTS_FILE        a file with arguments to pass to the native-image command
[INFO]     [creator]         $BP_NATIVE_IMAGE_BUILT_ARTIFACT              the built application artifact explicitly, required if building from a JAR
[INFO]     [creator]       Native Image: Contributing to layer
[INFO]     [creator]         Executing native-image -H:Name=/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication -cp /workspace:/workspace/BOOT-INF/classes:/workspace/BOOT-INF/lib/logback-classic-1.4.5.jar:/workspace/BOOT-INF/lib/logback-core-1.4.5.jar:/workspace/BOOT-INF/lib/log4j-to-slf4j-2.19.0.jar:/workspace/BOOT-INF/lib/log4j-api-2.19.0.jar:/workspace/BOOT-INF/lib/jul-to-slf4j-2.0.4.jar:/workspace/BOOT-INF/lib/jakarta.annotation-api-2.1.1.jar:/workspace/BOOT-INF/lib/snakeyaml-1.33.jar:/workspace/BOOT-INF/lib/spring-boot-actuator-autoconfigure-3.0.0.jar:/workspace/BOOT-INF/lib/spring-boot-actuator-3.0.0.jar:/workspace/BOOT-INF/lib/jackson-databind-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-annotations-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-core-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-datatype-jsr310-2.14.1.jar:/workspace/BOOT-INF/lib/micrometer-observation-1.10.2.jar:/workspace/BOOT-INF/lib/micrometer-commons-1.10.2.jar:/workspace/BOOT-INF/lib/micrometer-core-1.10.2.jar:/workspace/BOOT-INF/lib/HdrHistogram-2.1.12.jar:/workspace/BOOT-INF/lib/LatencyUtils-2.0.3.jar:/workspace/BOOT-INF/lib/spring-context-support-6.0.2.jar:/workspace/BOOT-INF/lib/spring-beans-6.0.2.jar:/workspace/BOOT-INF/lib/spring-context-6.0.2.jar:/workspace/BOOT-INF/lib/spring-aop-6.0.2.jar:/workspace/BOOT-INF/lib/aspectjweaver-1.9.9.1.jar:/workspace/BOOT-INF/lib/HikariCP-5.0.1.jar:/workspace/BOOT-INF/lib/spring-jdbc-6.0.2.jar:/workspace/BOOT-INF/lib/hibernate-core-6.1.5.Final.jar:/workspace/BOOT-INF/lib/jakarta.persistence-api-3.1.0.jar:/workspace/BOOT-INF/lib/jakarta.transaction-api-2.0.1.jar:/workspace/BOOT-INF/lib/jboss-logging-3.5.0.Final.jar:/workspace/BOOT-INF/lib/hibernate-commons-annotations-6.0.2.Final.jar:/workspace/BOOT-INF/lib/jandex-2.4.2.Final.jar:/workspace/BOOT-INF/lib/classmate-1.5.1.jar:/workspace/BOOT-INF/lib/byte-buddy-1.12.19.jar:/workspace/BOOT-INF/lib/jaxb-runtime-4.0.1.jar:/workspace/BOOT-INF/lib/jaxb-core-4.0.1.jar:/workspace/BOOT-INF/lib/angus-activation-1.0.0.jar:/workspace/BOOT-INF/lib/txw2-4.0.1.jar:/workspace/BOOT-INF/lib/istack-commons-runtime-4.1.1.jar:/workspace/BOOT-INF/lib/jakarta.inject-api-2.0.0.jar:/workspace/BOOT-INF/lib/antlr4-runtime-4.10.1.jar:/workspace/BOOT-INF/lib/spring-data-jpa-3.0.0.jar:/workspace/BOOT-INF/lib/spring-data-commons-3.0.0.jar:/workspace/BOOT-INF/lib/spring-orm-6.0.2.jar:/workspace/BOOT-INF/lib/spring-tx-6.0.2.jar:/workspace/BOOT-INF/lib/slf4j-api-2.0.4.jar:/workspace/BOOT-INF/lib/spring-aspects-6.0.2.jar:/workspace/BOOT-INF/lib/jackson-datatype-jdk8-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-module-parameter-names-2.14.1.jar:/workspace/BOOT-INF/lib/tomcat-embed-core-10.1.1.jar:/workspace/BOOT-INF/lib/tomcat-embed-websocket-10.1.1.jar:/workspace/BOOT-INF/lib/spring-web-6.0.2.jar:/workspace/BOOT-INF/lib/spring-webmvc-6.0.2.jar:/workspace/BOOT-INF/lib/spring-expression-6.0.2.jar:/workspace/BOOT-INF/lib/tomcat-embed-el-10.1.1.jar:/workspace/BOOT-INF/lib/hibernate-validator-8.0.0.Final.jar:/workspace/BOOT-INF/lib/jakarta.validation-api-3.0.2.jar:/workspace/BOOT-INF/lib/thymeleaf-spring6-3.1.0.RELEASE.jar:/workspace/BOOT-INF/lib/thymeleaf-3.1.0.RELEASE.jar:/workspace/BOOT-INF/lib/attoparser-2.0.6.RELEASE.jar:/workspace/BOOT-INF/lib/unbescape-1.1.6.RELEASE.jar:/workspace/BOOT-INF/lib/spring-core-6.0.2.jar:/workspace/BOOT-INF/lib/spring-jcl-6.0.2.jar:/workspace/BOOT-INF/lib/h2-2.1.214.jar:/workspace/BOOT-INF/lib/mysql-connector-j-8.0.31.jar:/workspace/BOOT-INF/lib/postgresql-42.5.1.jar:/workspace/BOOT-INF/lib/checker-qual-3.5.0.jar:/workspace/BOOT-INF/lib/cache-api-1.1.1.jar:/workspace/BOOT-INF/lib/caffeine-3.1.2.jar:/workspace/BOOT-INF/lib/error_prone_annotations-2.16.jar:/workspace/BOOT-INF/lib/bootstrap-5.1.3.jar:/workspace/BOOT-INF/lib/font-awesome-4.7.0.jar:/workspace/BOOT-INF/lib/spring-boot-3.0.0.jar:/workspace/BOOT-INF/lib/spring-boot-autoconfigure-3.0.0.jar:/workspace/BOOT-INF/lib/jakarta.xml.bind-api-4.0.0.jar:/workspace/BOOT-INF/lib/jakarta.activation-api-2.1.0.jar:/workspace/BOOT-INF/lib/spring-boot-jarmode-layertools-3.0.0.jar org.springframework.samples.petclinic.PetClinicApplication
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     GraalVM Native Image: Generating '/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication' (executable)...
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     [1/7] Initializing...                                           (13.5s @ 0.32GB)
[INFO]     [creator]      Version info: 'GraalVM 22.3.0 Java 17 CE'
[INFO]     [creator]      Java version info: '17.0.5+8-LTS'
[INFO]     [creator]      C compiler: gcc (linux, x86_64, 7.5.0)
[INFO]     [creator]      Garbage collector: Serial GC
[INFO]     [creator]      1 user-specific feature(s)
[INFO]     [creator]      - org.springframework.aot.nativex.feature.PreComputeFieldFeature
[INFO]     [creator]     The bundle named: org.apache.el.Messages, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#log4jSpiPresent set to true at build time
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#log4jSlf4jProviderPresent set to true at build time
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#slf4jSpiPresent set to true at build time
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#slf4jApiPresent set to true at build time
[INFO]     [creator]     Field org.springframework.core.NativeDetector#imageCode set to true at build time
[INFO]     [creator]     Field org.springframework.core.KotlinDetector#kotlinPresent set to false at build time
[INFO]     [creator]     Field org.springframework.core.KotlinDetector#kotlinReflectPresent set to false at build time
[INFO]     [creator]     Field org.springframework.cglib.core.AbstractClassGenerator#imageCode set to true at build time
[INFO]     [creator]     Field org.springframework.format.support.DefaultFormattingConversionService#jsr354Present set to false at build time
[INFO]     [creator]     [2/7] Performing analysis...  [**********]                      (40.6s @ 4.69GB)
[INFO]     [creator]       10,239 (89.52%) of 11,438 classes reachable
[INFO]     [creator]       16,688 (63.45%) of 26,300 fields reachable
[INFO]     [creator]       48,570 (58.24%) of 83,401 methods reachable
[INFO]     [creator]          472 classes,   144 fields, and 2,321 methods registered for reflection
[INFO]     [creator]           63 classes,    68 fields, and    55 methods registered for JNI access
[INFO]     [creator]            4 native libraries: dl, pthread, rt, z
[INFO]     [creator]     [3/7] Building universe...                                       (6.0s @ 2.62GB)
[INFO]     [creator]     
[INFO]     [creator]     Warning: Dynamic proxy method java.lang.reflect.Proxy.newProxyInstance invoked at org.springframework.beans.factory.support.AutowireUtils.resolveAutowiringValue(AutowireUtils.java:134)
[INFO]     [creator]     Warning: Dynamic proxy method java.lang.reflect.Proxy.newProxyInstance invoked at org.springframework.core.annotation.SynthesizedMergedAnnotationInvocationHandler.createProxy(SynthesizedMergedAnnotationInvocationHandler.java:304)
[INFO]     [creator]     Warning: Dynamic proxy method java.lang.reflect.Proxy.newProxyInstance invoked at org.springframework.core.io.support.VfsPatternUtils.visit(VfsPatternUtils.java:51)
[INFO]     [creator]     Warning: Aborting stand-alone image build due to dynamic proxy use without configuration.
[INFO]     [creator]     Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]         2.8s (4.6% of total time) in 23 GCs | Peak RSS: 6.05GB | CPU load: 5.55
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     Failed generating '/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication' after 1m 0s.
[INFO]     [creator]     Generating fallback image...
[INFO]     [creator]     Warning: Image '/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
[INFO]     [creator]       Removing bytecode
[INFO]     [creator]       Process types:
[INFO]     [creator]         native-image: /workspace/org.springframework.samples.petclinic.PetClinicApplication (direct)
[INFO]     [creator]         task:         /workspace/org.springframework.samples.petclinic.PetClinicApplication (direct)
[INFO]     [creator]         web:          /workspace/org.springframework.samples.petclinic.PetClinicApplication (direct)
[...]
```

The worrying part being:

```
[INFO]     [creator]     Failed generating '/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication' after 1m 0s.
[INFO]     [creator]     Generating fallback image...
[INFO]     [creator]     Warning: Image '/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
```

and when I try to run this fallback image, I get:

```
$ docker run -p 8080:8080  -it docker.io/library/spring-petclinic:3.0.0-SNAPSHOT
Error: No bin/java and no environment variable JAVA_HOME
```

**Comment by anthonydahanne** [comment]
then I retried using `--no-fallback` adding this to my pom.xml:

```
[...]
<BP_NATIVE_IMAGE_BUILD_ARGUMENTS>--no-fallback</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
[...]
```

and although it successfully built the "default" image:
```
[INFO]     [creator]     Paketo Buildpack for Native Image 5.6.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/native-image
[INFO]     [creator]       Build Configuration:
[INFO]     [creator]         $BP_BINARY_COMPRESSION_METHOD                         Compression mechanism used to reduce binary size. Options: `none` (default), `upx` or `gzexe`
[INFO]     [creator]         $BP_NATIVE_IMAGE                       true           enable native image build
[INFO]     [creator]         $BP_NATIVE_IMAGE_BUILD_ARGUMENTS       --no-fallback  arguments to pass to the native-image command
[INFO]     [creator]         $BP_NATIVE_IMAGE_BUILD_ARGUMENTS_FILE                 a file with arguments to pass to the native-image command
[INFO]     [creator]         $BP_NATIVE_IMAGE_BUILT_ARTIFACT                       the built application artifact explicitly, required if building from a JAR
[INFO]     [creator]       Native Image: Contributing to layer
[INFO]     [creator]         Executing native-image --no-fallback -H:Name=/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication -cp /workspace:/workspace/BOOT-INF/classes:/workspace/BOOT-INF/lib/logback-classic-1.4.5.jar:/workspace/BOOT-INF/lib/logback-core-1.4.5.jar:/workspace/BOOT-INF/lib/log4j-to-slf4j-2.19.0.jar:/workspace/BOOT-INF/lib/log4j-api-2.19.0.jar:/workspace/BOOT-INF/lib/jul-to-slf4j-2.0.4.jar:/workspace/BOOT-INF/lib/jakarta.annotation-api-2.1.1.jar:/workspace/BOOT-INF/lib/snakeyaml-1.33.jar:/workspace/BOOT-INF/lib/spring-boot-actuator-autoconfigure-3.0.0.jar:/workspace/BOOT-INF/lib/spring-boot-actuator-3.0.0.jar:/workspace/BOOT-INF/lib/jackson-databind-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-annotations-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-core-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-datatype-jsr310-2.14.1.jar:/workspace/BOOT-INF/lib/micrometer-observation-1.10.2.jar:/workspace/BOOT-INF/lib/micrometer-commons-1.10.2.jar:/workspace/BOOT-INF/lib/micrometer-core-1.10.2.jar:/workspace/BOOT-INF/lib/HdrHistogram-2.1.12.jar:/workspace/BOOT-INF/lib/LatencyUtils-2.0.3.jar:/workspace/BOOT-INF/lib/spring-context-support-6.0.2.jar:/workspace/BOOT-INF/lib/spring-beans-6.0.2.jar:/workspace/BOOT-INF/lib/spring-context-6.0.2.jar:/workspace/BOOT-INF/lib/spring-aop-6.0.2.jar:/workspace/BOOT-INF/lib/aspectjweaver-1.9.9.1.jar:/workspace/BOOT-INF/lib/HikariCP-5.0.1.jar:/workspace/BOOT-INF/lib/spring-jdbc-6.0.2.jar:/workspace/BOOT-INF/lib/hibernate-core-6.1.5.Final.jar:/workspace/BOOT-INF/lib/jakarta.persistence-api-3.1.0.jar:/workspace/BOOT-INF/lib/jakarta.transaction-api-2.0.1.jar:/workspace/BOOT-INF/lib/jboss-logging-3.5.0.Final.jar:/workspace/BOOT-INF/lib/hibernate-commons-annotations-6.0.2.Final.jar:/workspace/BOOT-INF/lib/jandex-2.4.2.Final.jar:/workspace/BOOT-INF/lib/classmate-1.5.1.jar:/workspace/BOOT-INF/lib/byte-buddy-1.12.19.jar:/workspace/BOOT-INF/lib/jaxb-runtime-4.0.1.jar:/workspace/BOOT-INF/lib/jaxb-core-4.0.1.jar:/workspace/BOOT-INF/lib/angus-activation-1.0.0.jar:/workspace/BOOT-INF/lib/txw2-4.0.1.jar:/workspace/BOOT-INF/lib/istack-commons-runtime-4.1.1.jar:/workspace/BOOT-INF/lib/jakarta.inject-api-2.0.0.jar:/workspace/BOOT-INF/lib/antlr4-runtime-4.10.1.jar:/workspace/BOOT-INF/lib/spring-data-jpa-3.0.0.jar:/workspace/BOOT-INF/lib/spring-data-commons-3.0.0.jar:/workspace/BOOT-INF/lib/spring-orm-6.0.2.jar:/workspace/BOOT-INF/lib/spring-tx-6.0.2.jar:/workspace/BOOT-INF/lib/slf4j-api-2.0.4.jar:/workspace/BOOT-INF/lib/spring-aspects-6.0.2.jar:/workspace/BOOT-INF/lib/jackson-datatype-jdk8-2.14.1.jar:/workspace/BOOT-INF/lib/jackson-module-parameter-names-2.14.1.jar:/workspace/BOOT-INF/lib/tomcat-embed-core-10.1.1.jar:/workspace/BOOT-INF/lib/tomcat-embed-websocket-10.1.1.jar:/workspace/BOOT-INF/lib/spring-web-6.0.2.jar:/workspace/BOOT-INF/lib/spring-webmvc-6.0.2.jar:/workspace/BOOT-INF/lib/spring-expression-6.0.2.jar:/workspace/BOOT-INF/lib/tomcat-embed-el-10.1.1.jar:/workspace/BOOT-INF/lib/hibernate-validator-8.0.0.Final.jar:/workspace/BOOT-INF/lib/jakarta.validation-api-3.0.2.jar:/workspace/BOOT-INF/lib/thymeleaf-spring6-3.1.0.RELEASE.jar:/workspace/BOOT-INF/lib/thymeleaf-3.1.0.RELEASE.jar:/workspace/BOOT-INF/lib/attoparser-2.0.6.RELEASE.jar:/workspace/BOOT-INF/lib/unbescape-1.1.6.RELEASE.jar:/workspace/BOOT-INF/lib/spring-core-6.0.2.jar:/workspace/BOOT-INF/lib/spring-jcl-6.0.2.jar:/workspace/BOOT-INF/lib/h2-2.1.214.jar:/workspace/BOOT-INF/lib/mysql-connector-j-8.0.31.jar:/workspace/BOOT-INF/lib/postgresql-42.5.1.jar:/workspace/BOOT-INF/lib/checker-qual-3.5.0.jar:/workspace/BOOT-INF/lib/cache-api-1.1.1.jar:/workspace/BOOT-INF/lib/caffeine-3.1.2.jar:/workspace/BOOT-INF/lib/error_prone_annotations-2.16.jar:/workspace/BOOT-INF/lib/bootstrap-5.1.3.jar:/workspace/BOOT-INF/lib/font-awesome-4.7.0.jar:/workspace/BOOT-INF/lib/spring-boot-3.0.0.jar:/workspace/BOOT-INF/lib/spring-boot-autoconfigure-3.0.0.jar:/workspace/BOOT-INF/lib/jakarta.xml.bind-api-4.0.0.jar:/workspace/BOOT-INF/lib/jakarta.activation-api-2.1.0.jar:/workspace/BOOT-INF/lib/spring-boot-jarmode-layertools-3.0.0.jar org.springframework.samples.petclinic.PetClinicApplication
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     GraalVM Native Image: Generating '/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication' (executable)...
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     [1/7] Initializing...                                           (13.1s @ 0.54GB)
[INFO]     [creator]      Version info: 'GraalVM 22.3.0 Java 17 CE'
[INFO]     [creator]      Java version info: '17.0.5+8-LTS'
[INFO]     [creator]      C compiler: gcc (linux, x86_64, 7.5.0)
[INFO]     [creator]      Garbage collector: Serial GC
[INFO]     [creator]      1 user-specific feature(s)
[INFO]     [creator]      - org.springframework.aot.nativex.feature.PreComputeFieldFeature
[INFO]     [creator]     The bundle named: org.apache.el.Messages, has not been found. If the bundle is part of a module, verify the bundle name is a fully qualified class name. Otherwise verify the bundle path is accessible in the classpath.
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#log4jSpiPresent set to true at build time
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#log4jSlf4jProviderPresent set to true at build time
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#slf4jSpiPresent set to true at build time
[INFO]     [creator]     Field org.apache.commons.logging.LogAdapter#slf4jApiPresent set to true at build time
[INFO]     [creator]     Field org.springframework.core.NativeDetector#imageCode set to true at build time
[INFO]     [creator]     Field org.springframework.core.KotlinDetector#kotlinPresent set to false at build time
[INFO]     [creator]     Field org.springframework.core.KotlinDetector#kotlinReflectPresent set to false at build time
[INFO]     [creator]     Field org.springframework.format.support.DefaultFormattingConversionService#jsr354Present set to false at build time
[INFO]     [creator]     Field org.springframework.cglib.core.AbstractClassGenerator#imageCode set to true at build time
[INFO]     [creator]     [2/7] Performing analysis...  [**********]                      (39.7s @ 3.04GB)
[INFO]     [creator]       10,239 (89.52%) of 11,438 classes reachable
[INFO]     [creator]       16,688 (63.45%) of 26,300 fields reachable
[INFO]     [creator]       48,570 (58.24%) of 83,401 methods reachable
[INFO]     [creator]          472 classes,   144 fields, and 2,321 methods registered for reflection
[INFO]     [creator]           63 classes,    68 fields, and    55 methods registered for JNI access
[INFO]     [creator]            4 native libraries: dl, pthread, rt, z
[INFO]     [creator]     [3/7] Building universe...                                       (5.2s @ 1.01GB)
[INFO]     [creator]     [4/7] Parsing methods...      [**]                               (3.9s @ 4.43GB)
[INFO]     [creator]     [5/7] Inlining methods...     [***]                              (2.1s @ 1.95GB)
[INFO]     [creator]     [6/7] Compiling methods...    [*****]                           (28.5s @ 2.47GB)
[INFO]     [creator]     [7/7] Creating image...                                          (4.8s @ 4.19GB)
[INFO]     [creator]       22.73MB (42.56%) for code area:    31,483 compilation units
[INFO]     [creator]       28.97MB (54.25%) for image heap:  283,689 objects and 685 resources
[INFO]     [creator]        1.70MB ( 3.19%) for other data
[INFO]     [creator]       53.40MB in total
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]     Top 10 packages in code area:           Top 10 object types in image heap:
[INFO]     [creator]        1.63MB sun.security.ssl                 6.55MB byte[] for embedded resources
[INFO]     [creator]      978.17KB java.util                        4.88MB byte[] for code metadata
[INFO]     [creator]      832.54KB java.lang.invoke                 2.55MB java.lang.String
[INFO]     [creator]      716.25KB com.sun.crypto.provider          2.54MB byte[] for general heap data
[INFO]     [creator]      492.43KB org.apache.tomcat.util.net       2.38MB java.lang.Class
[INFO]     [creator]      464.80KB java.lang                        1.90MB byte[] for java.lang.String
[INFO]     [creator]      461.85KB sun.security.x509              879.91KB c.o.s.c.h.DynamicHubCompanion
[INFO]     [creator]      447.28KB c.s.o.a.x.i.i.xs.traversers    579.94KB java.util.HashMap$Node
[INFO]     [creator]      423.98KB c.s.o.a.xerces.internal.impl   527.19KB byte[] for reflection metadata
[INFO]     [creator]      400.26KB java.util.concurrent           513.09KB int[][]
[INFO]     [creator]       15.77MB for 396 more packages            5.02MB for 2309 more object types
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]         3.0s (3.0% of total time) in 34 GCs | Peak RSS: 6.37GB | CPU load: 5.95
[INFO]     [creator]     --------------------------------------------------------------------------------
[INFO]     [creator]     Produced artifacts:
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication (executable)
[INFO]     [creator]      /layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication.build_artifacts.txt (txt)
[INFO]     [creator]     ================================================================================
[INFO]     [creator]     Finished generating '/layers/paketo-buildpacks_native-image/native-image/org.springframework.samples.petclinic.PetClinicApplication' in 1m 42s.
[INFO]     [creator]       Removing bytecode
[INFO]     [creator]       Process types:
[INFO]     [creator]         native-image: /workspace/org.springframework.samples.petclinic.PetClinicApplication (direct)
[INFO]     [creator]         task:         /workspace/org.springframework.samples.petclinic.PetClinicApplication (direct)
[INFO]     [creator]         web:          /workspace/org.springframework.samples.petclinic.PetClinicApplication (direct)
```

the image was still non usable:

```
docker run -p 8080:8080  -it spring-petclinic:3.0.0-SNAPSHOT

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.0)

18:23:50.110 [main] DEBUG org.springframework.context.aot.AotApplicationContextInitializer - Initializing ApplicationContext with AOT
18:23:50.111 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: Could not find class [org.springframework.samples.petclinic.PetClinicApplication__ApplicationContextInitializer]
        at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:333)
        at org.springframework.context.aot.AotApplicationContextInitializer.instantiateInitializer(AotApplicationContextInitializer.java:80)
        at org.springframework.context.aot.AotApplicationContextInitializer.initialize(AotApplicationContextInitializer.java:71)
        at org.springframework.context.aot.AotApplicationContextInitializer.lambda$forInitializerClasses$0(AotApplicationContextInitializer.java:61)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:603)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:383)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
        at org.springframework.samples.petclinic.PetClinicApplication.main(PetClinicApplication.java:34)
Caused by: java.lang.ClassNotFoundException: org.springframework.samples.petclinic.PetClinicApplication__ApplicationContextInitializer
        at java.base@17.0.5/java.lang.Class.forName(DynamicHub.java:1132)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:283)
        at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:323)
        ... 9 common frames omitted
```

**Comment by ksilz** [comment]
Thank you, @anthonydahanne! I figured that there'll be dragons somewhere down the line. 😒

**Comment by DuncanCasteleyn** [comment]
After #1135 I was able to get this working as a native docker image when the native profile is active. to create a native executable (without docker) I had to comment out spring boot devtools in the pom.xml it would be enabled en cause start-up to fail.

Besides that all you would have to do is add the graalvm plugin as mentioned in the spring boot reference guide.

**Comment by patbaumgartner** [comment]
I can confirm, that adding the 

```xml
      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
      </plugin>
```

creates a native image, when building the image with native profile. Even though the resource bundles (messages) are not loaded.

**Comment by dsyer** [comment]
This should work out of the box now since the release of Spring Boot 3.
