### ISSUE TITLE
Jetty 9 support

### ISSUE THREAD

**Issue by arey** [spring-projects/spring-petclinic#171]
The Spring petlinic does not work on Jetty 9. The DandelionFilter throws an org.eclipse.jetty.io.EofException.
I've open an issue on the Dandelion project: https://github.com/dandelion/dandelion/issues/113
Either we are waiting a fix or we replace Dandelion by another solution.

**Comment by meltsufin** [comment]
I'm not seeing that particular error from the DandelionFilter, but after the application starts up with the jetty:run and I go to /petclinic, I get a blank page and no errors in the log.

I'm using this Jetty plugin:
```XML
<plugin>
  <groupId>org.eclipse.jetty</groupId>
  <artifactId>jetty-maven-plugin</artifactId>
  <version>9.3.11.M0</version>
</plugin>
```

**Comment by janbartel** [comment]
@meltsufin if you try a different url like /petclinic/index.html you will get the exception from the Dandelion filter when using jetty-9.3.11.  Interestingly if I use jetty-9.2.17 then I don't see the exception, however that may just be a change in the way jetty reports the error. I'm looking into jetty.

**Comment by janbartel** [comment]
Using jetty-9.4 head, the exception is slightly different, but still generated from the dandelion filter:
java.lang.IllegalArgumentException: setContentLength(0) when already written 335
	at org.eclipse.jetty.server.Response.setContentLength(Response.java:921)
	at com.github.dandelion.core.web.handler.impl.AssetInjectionPostHandler.handle(AssetInjectionPostHandler.java:199)
	at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:68)
	at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73)
	at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:145)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1547)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1547)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1589)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1213)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1552)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1126)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:550)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:321)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:254)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:269)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

**Comment by janbartel** [comment]
Another dandelion issue that seems  very relevant: https://github.com/dandelion/dandelion/issues/91

**Comment by janbartel** [comment]
A pull request for Dandelion has been submitted that fixes the response wrapper so it correctly implements the servlet spec contract for getWriter() and getOutputStream().  For an explanation of what is wrong with it, refer to [jetty issue 759](https://github.com/eclipse/jetty.project/issues/759).

https://github.com/dandelion/dandelion/pull/116

**Comment by arey** [comment]
Thanks a lot @janbartel and @gregw for all your work. I’ve tested the ByteArrayResponseWrapper version you proposed in the PR #116. With it, Petclinic is working fine on Jetty 9, Tomcat 7 and 8. I’m waiting it will integrated into a next Dandelion release. I see any commits since 10 months ago. So I will contact by email @tduchateau to know if Dandelion is still alive.

**Comment by meltsufin** [comment]
@arey Did you get a response from @tduchateau? It appears as though Dandelion may no longer be maintained. If that's the case, any plans going forward?

**Comment by arey** [comment]
@meltsufin I don't receive any answer to the email I've sent to @tduchateau 
As you notice, the Dandelion project seems to be not maintained. I'm still waiting a few weeks. Then we should decide to move to another solution for our table.

**Comment by arey** [comment]
Tech lead of the Dandelion, Thibault Duchateau answered that we have to remove Dandelion.
