### ISSUE TITLE
Update presentation on speakerdeck with Spring Boot features

### ISSUE THREAD

**Issue by arey** [spring-projects/spring-petclinic#204]
Nowadays the master branch is holding the Spring Boot version of Spring Petclinic, it would be great to update the presentation referenced by the readme.md:
https://speakerdeck.com/michaelisvy/spring-petclinic-sample-application

**Comment by arey** [comment]
I've updated the presentation of the legacy version of Spring Petclinic: http://fr.slideshare.net/AntoineRey/spring-framework-petclinic-sample-application
@dsyer you may use these slides if you are interested

**Comment by ramprasad6** [comment]
i have run the mvn compile ,Post compile am getiing below error,Please check and suggest .**

error:
root@vagrant-ubuntu-trusty-64:/home/vagrant/spring-petclinic# mvnw compile
No command 'mvnw' found, did you mean:
 Command 'mvn' from package 'maven2' (universe)
 Command 'mvn' from package 'maven' (universe)
mvnw: command not found
root@vagrant-ubuntu-trusty-64:/home/vagrant/spring-petclinic# clear
root@vagrant-ubuntu-trusty-64:/home/vagrant/spring-petclinic# mvn compile
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.ArrayIndexOutOfBoundsException: 9389 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ArrayIndexOutOfBoundsException: 9389
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 9389
        at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2470)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1257)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextTag(MXParser.java:1090)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parsePluginExecution(MavenXpp3ReaderEx.java:3507)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parsePlugin(MavenXpp3ReaderEx.java:3302)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseBuildBase(MavenXpp3ReaderEx.java:1364)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseProfile(MavenXpp3ReaderEx.java:3717)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseModel(MavenXpp3ReaderEx.java:2775)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4631)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4590)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:118)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:91)
        at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:77)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:456)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:261)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:343)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        ... 11 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
root@vagrant-ubuntu-trusty-64:/home/vagrant/spring-petclinic#

**Comment by dsyer** [comment]
I think you meant to type `./mvnw…`?

**Comment by gaurav-91** [comment]
@arey Is the presentation slide link mentioned in Readme updated or it is pending? Because I was just trying to refer those but looks like they are still pointing to the https://github.com/spring-petclinic/spring-framework-petclinic resource rather than https://github.com/spring-projects/spring-petclinic. Please advise or am I missing  something here?

**Comment by arey** [comment]
Hi @gaurav-91. Unfortunately, this Slideshare presentation has never been updated to reflect the software architecture and the technical stack of this version of Spring Petclinic based on Spring Boot. It refers to a previous version backup in the [spring-petclinic GitHub organization](https://github.com/spring-petclinic).
This situation may disturb developers like you discovering this project.
