### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by ruchikagarg23** [spring-projects/spring-petclinic#244]
Hi,

When I am trying to use mysql database, I am getting below error
aused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver 
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 41 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver 
	at org.springframework.util.Assert.state(Assert.java:70)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:231)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:183)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:42)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Tomcat.dataSource(DataSourceConfiguration.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 42 common frames omitted

I have modified application. properties.
I have dependency jar in maven repository as well.

**Comment by dsyer** [comment]
Looks like a bad jar probably. Did you try deleting it and starting again?

**Comment by snicoll** [comment]
Closing due to lack of feedback. @ruchikagarg23 if you provide us more info we can reopen.

**Comment by ramnar** [comment]
thanks dsyer the solution worked for me

**Comment by Sumeet-Varma** [comment]
In my case the issue comes in following configurations :-

Spring Boot 2.1.5  
Dependency Used:- spring-boot-starter-data-jpa, mysql-connector-java (default 8.0.16) only  

In application.properties file NOW a days it seems like we can't use :- spring.datasource.driverClassName 
INSTEAD we can use:- spring.datasource.driver-class-name  BUT I have seen so many examples with  'spring.datasource.driverClassName'.
