### ISSUE TITLE
Mysql database Change Error

### ISSUE THREAD

**Issue by ahmetgire** [spring-projects/spring-petclinic#282]
When I want to change database to mysql database and run application I am taking this error:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Failed to replace DataSource with an embedded database for tests. If you want an embedded database please put a supported one on the classpath or tune the replace attribute of @AutoconfigureTestDatabase.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
```

How can I fix it?

**Comment by dsyer** [comment]
How did you do that? You should be able to just run the app with `spring.profiles.active=mysql`. Works for me.

**Comment by snicoll** [comment]
@ahmetgire it's been a while so I am going to close this one. If you can share the information @dsyer has requested, we can reopen for sure.
