### ISSUE TITLE
PostgreSQL / MySQL constraint violation

### ISSUE THREAD

**Issue by ascheman** [spring-projects/spring-petclinic#936]
Creating new items when using PostgreSQL or MySQL results in constraint violations like this: 

```
could not execute statement; SQL [n/a]; constraint [pets_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
```

IDs are already used by predefined database entries.

**Comment by dsyer** [comment]
It seems to work for me, but I can sort of understand why it might fail because the ids are hard-coded in the `data.sql` initialization. What did you do exactly to make it fail?

**Comment by mikesindieiev** [comment]
> It seems to work for me, but I can sort of understand why it might fail because the ids are hard-coded in the `data.sql` initialization. What did you do exactly to make it fail?

I've got same issue. 
I've just start posrtgres from docker-compose file (`docker-compose up -d postgres`
) and run petclinic application (java -Dspring.profiles.active=postgres -jar build/libs/*.jar)

**Comment by ascheman** [comment]
What @mikesindieiev says.

**Comment by dsyer** [comment]
What did you do to get that error though? I’m not saying it isn’t a problem, I just don’t know how to reproduce it.

**Comment by ascheman** [comment]
```
$ java -version

openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)
```

```
$ git log | head

commit d381fb658cb435a04e2271ca85bd3e8627a5e7e4
Author: Dave Syer <dsyer@vmware.com>
Date:   Mon Apr 11 13:24:49 2022 +0000
```

```
$ ./mvnw clean package

...
[INFO] --- spring-boot-maven-plugin:2.6.6:repackage (repackage) @ spring-petclinic ---
[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.112 s
[INFO] Finished at: 2022-04-19T09:19:24+02:00
```

```
$ docker-compose up -d postgres

[+] Running 2/2
 ⠿ Network spring-petclinic_default       Created                                                                                                                                                                                          0.0s
 ⠿ Container spring-petclinic-postgres-1  Started
```

```
$ java  -Dserver.port=8888 -Dspring.profiles.active=postgres -jar target/spring-petclinic-2.6.0-SNAPSHOT.jar

:: Built with Spring Boot :: 2.6.6


2022-04-19 09:22:43.117  INFO 92550 --- [           main] o.s.s.petclinic.PetClinicApplication     : Starting PetClinicApplication v2.6.0-SNAPSHOT using Java 11.0.14 on godestorm.fritz.box with PID 92550 (/Users/ascheman/wrk/javaland/2022/perf-ws/spring-petclinic/target/spring-petclinic-2.6.0-SNAPSHOT.jar started by ascheman in /Users/ascheman/wrk/javaland/2022/perf-ws/spring-petclinic)
2022-04-19 09:22:43.120  INFO 92550 --- [           main] o.s.s.petclinic.PetClinicApplication     : The following 1 profile is active: "postgres"
2022-04-19 09:22:44.031  INFO 92550 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-04-19 09:22:44.081  INFO 92550 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 39 ms. Found 2 JPA repository interfaces.
2022-04-19 09:22:44.851  INFO 92550 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8888 (http)
2022-04-19 09:22:44.875  INFO 92550 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-04-19 09:22:44.876  INFO 92550 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.60]
2022-04-19 09:22:45.003  INFO 92550 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-04-19 09:22:45.003  INFO 92550 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1831 ms
2022-04-19 09:22:45.326  INFO 92550 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-04-19 09:22:45.584  INFO 92550 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-04-19 09:22:46.214  INFO 92550 --- [           main] org.ehcache.core.EhcacheManager          : Cache 'vets' created in EhcacheManager.
2022-04-19 09:22:46.229  INFO 92550 --- [           main] org.ehcache.jsr107.Eh107CacheManager     : Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=vets
2022-04-19 09:22:46.237  INFO 92550 --- [           main] org.ehcache.jsr107.Eh107CacheManager     : Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=vets
2022-04-19 09:22:46.320  INFO 92550 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-04-19 09:22:46.384  INFO 92550 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.7.Final
2022-04-19 09:22:46.538  INFO 92550 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-04-19 09:22:46.672  INFO 92550 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
2022-04-19 09:22:47.376  INFO 92550 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-04-19 09:22:47.386  INFO 92550 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-04-19 09:22:49.030  INFO 92550 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 13 endpoint(s) beneath base path '/actuator'
2022-04-19 09:22:49.103  INFO 92550 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8888 (http) with context path ''
2022-04-19 09:22:49.123  INFO 92550 --- [           main] o.s.s.petclinic.PetClinicApplication     : Started PetClinicApplication in 6.476 seconds (JVM running for 6.933)
```

```
$ open http://localhost:8888
```

-> Find Owners -> Add Owner -> Fill out fields -> Click "Add Owner" button

<img width="353" alt="image" src="https://user-images.githubusercontent.com/456000/163948465-5805ad4e-b72d-4ef4-a85b-9fe3c8d95b01.png">

```
2022-04-19 09:24:17.963  WARN 92550 --- [nio-8888-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23505
2022-04-19 09:24:17.963 ERROR 92550 --- [nio-8888-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: duplicate key value violates unique constraint "owners_pkey"
  Detail: Key (id)=(1) already exists.
2022-04-19 09:24:17.978 ERROR 92550 --- [nio-8888-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [owners_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "owners_pkey"
  Detail: Key (id)=(1) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.3.jar!/:42.3.3]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[postgresql-42.3.3.jar!/:42.3.3]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[postgresql-42.3.3.jar!/:42.3.3]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[postgresql-42.3.3.jar!/:42.3.3]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) ~[postgresql-42.3.3.jar!/:42.3.3]
```

**Comment by dsyer** [comment]
It still works for me without any changes for MySQL, so I'm confused about that. Anyway Postgres should work too now.
